# Write your MySQL query statement below
SELECT 
ROUND(
    SUM(
        CASE 
        WHEN A.EVENT_DATE=DATE_ADD(B.FIRSTDATE , INTERVAL 1 DAY ) THEN 1 
        ELSE 0
        END
    )*1.00/ COUNT( DISTINCT A.PLAYER_ID),2) AS FRACTION 
FROM ACTIVITY A
JOIN (
SELECT PLAYER_ID, MIN(EVENT_DATE) AS FIRSTDATE
FROM ACTIVITY 
GROUP BY PLAYER_ID ) B
ON A.PLAYER_ID =B.PLAYER_ID